server:
  port: 30148
  servlet:
    context-path: /h-sm
    session:
      cookie:
        http-only: true
        max-age: ${spring.mvc.interceptors.login.cookie-max-age-sec}
        secure: false
        same-site: strict
        path: /
      timeout: 30m

mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
    - classpath*:**/mapper/common/*Mapper.xml
    - classpath*:**/mapper/embedded/*Mapper.xml
  config-location: classpath:jpaConfig-embedded.xml
mybatis-plus:
  mapper-locations: ${mybatis.mapper-locations}
  config-location: ${mybatis.config-location}

spring:
  application:
    name: h-sm
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/message
    encoding: UTF-8
  mvc:
    interceptors:
      mdc:
        enabled: true
      api-safe:
        enabled: true
        include-path-patterns:
          - /hbq969-dict/**
          - /hbq969-tabula/**
        header-name: api-safe-token
        header-value-regex: 8DC75E91D4E143CF94BA29C46C43B24B
      login:
        enabled: false
        cookie-max-age-sec: 1800
        dialect: embedded
        include-urls:
          - "/hbq969-common/**"
          - "/hbq969-sm/**"
          - "/hbq969-dict/**"
          - "/hbq969-tabula/**"
          - "/common/encrypt/**"
          - "/ui-gw/**"
        exclude-urls:
          - "/**/error"
          - "/common/health"
          - "/hbq969-sm/index.html"
          - "/hbq969-sm/**/*.js"
          - "/hbq969-sm/**/*.css"
          - "/hbq969-sm/**/*.png"
          - "/hbq969-sm/**/*.jpg"
          - "/hbq969-sm/**/*.map"
          - "/hbq969-sm/**/*.ico"
          - "/hbq969-sm/**/login"
      resource-handler-registry:
        entries:
          - handlers: /hbq969-common/**
            locations: classpath:/static/hbq969-common/
          - handlers: /hbq969-dict/**
            locations: classpath:/static/hbq969-dict/
          - handlers: /hbq969-tabula/**
            locations: classpath:/static/hbq969-tabula/
          - handlers: /hbq969-sm/**
            locations: classpath:/static/hbq969-sm/
        enabled: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:h2:mem:local
      driver-class-name: org.h2.Driver
      username: foo
      password: ENC(2HRE3Jhuz6IfiD8L7orn4flpXNPTWLhH4u6lH/i0SWf8jXh3tNGQG++plhHmJN3F)
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  kafka:
    producer:
      bootstrap-servers: docker.for.mac.host.internal:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      buffer-memory: 134217728
      batch-size: 65536
      properties:
        heartbeat.interval.ms: 3000
        max.block.ms: 10000
        #        sasl.mechanism: PLAIN
        #        security.protocol: SASL_PLAINTEXT
        #        sasl.jaas.config: ENC(wfUFL/Omh6mpEt2J/tJteC5jONhfnZD+9hR+4Mc7bnJnKwh6yhC8xMRv6yQl0dJTy5FhGlM7B8ubmI5VLFw6haz9wMBUcKwNkp4X+ktPNNj8OZaGkHvSITTeXS4KhMuNnUE9842xrRtCsqTbUPf+EhxnrrGof9Hnx7BjvgRgdq9CoQGm/dZsKPhY5nKjhU8B)
        retry.backoff.ms: 500
        linger.ms: 1000
        max.in.flight.requests.per.connection: 1
      retries: 120
    consumer:
      enabled: true
      bootstrap-servers: docker.for.mac.host.internal:9092
      enable-auto-commit: true
      auto-commit-interval: 10s
      max-poll-records: 500
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}
      fetch-min-size: 10485760
      fetch-max-wait: 2s
      properties:
        heartbeat.interval.ms: 3000
        max.block.ms: 10000
    #        sasl.mechanism: PLAIN
    #        security.protocol: SASL_PLAINTEXT
    #        sasl.jaas.config: ENC(wfUFL/Omh6mpEt2J/tJteC5jONhfnZD+9hR+4Mc7bnJnKwh6yhC8xMRv6yQl0dJTy5FhGlM7B8ubmI5VLFw6haz9wMBUcKwNkp4X+ktPNNj8OZaGkHvSITTeXS4KhMuNnUE9842xrRtCsqTbUPf+EhxnrrGof9Hnx7BjvgRgdq9CoQGm/dZsKPhY5nKjhU8B)
    listener:
      type: batch
      concurrency: 1
      poll-timeout: 10s

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: 123456

swagger:
  base-package: com
  api-info:
    title: web应用Restful API
    description: web应用Restful API
    termsOfServiceUrl: http://127.0.0.1:${server.port}
    version: v1.0
    license: Apache LICENSE-2.0
    licenseUrl: https://apache.org/licenses/LICENSE-2.0.txt

dict:
  enabled: true
  reload:
    cron: 0 */30 * * * *
  map-key-prefix: fmt

encrypt:
  config:
    enabled: true
  restful:
    enabled: true
    aes:
      key: DC2EE8931E434A44
      show-log: true

advice:
  log:
    enabled: true
  restful-limit:
    enabled: true

tabula:
  enabled: true
  dialect: mysql
  schema: openstack
  open-edit-delete: true